# Generated by Django 3.2.4 on 2021-06-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
